---
title: "Accuracy Measures"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Accuracy Measures}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Notation

- $t$-year event status: $D_t = I(T \leq t)$

- True Positive Rate: $\text{TPR}_t(z) = P(Z \geq z | D_t = 1)$

- False Positive Rate: $\text{FPR}_t(z) = P(Z \geq z | D_t = 0)$

- Receiver Operating Characteristic: $\text{ROC}_t(u) = \text{TPR}_t\{\text{FPR}_t^{-1}(u)\}$

- Area Under Curve: $\text{AUC}_t = \int \text{ROC}_t(u) du$

## Estimation

- $\widehat{\Lambda}_0(t) = \sum_{m=1}^t \widehat{\lambda}_{0m}$

- $\widehat{S}(t | Z_i) = \exp[-\hat{\Lambda}_0(t) \exp\{{\widehat{\beta} ^\top \psi(Z_i)}\}]$

- $\widehat{\text{TPR}}_t(z) = \dfrac{\sum_{i=1}^n \{1 - \widehat{S}(t | Z_i)\} I(Z_i \geq z)}{\sum_{i=1}^n \{1 - \widehat{S}(t | Z_i)\}}$

- $\widehat{\text{FPR}}_t(z) = \dfrac{\sum_{i=1}^n \widehat{S}(t | Z_i) I(Z_i \geq z)}{\sum_{i=1}^n \widehat{S}(t | Z_i)}$

- $\widehat{\text{AUC}}_t = \int \widehat{\text{TPR}}_t\{\widehat{\text{FPR}}_t^{-1}(u)\} du$

## References

- T. Cai, S. Cheng, Robust combination of multiple diagnostic tests for classifying censored event times, _Biostatistics_, Volume 9, Issue 2, April 2008, Pages 216–233, https://doi.org/10.1093/biostatistics/kxm037

- Hajime Uno, Tianxi Cai, Lu Tian & L. J Wei (2007) Evaluating Prediction Rules for t-Year Survivors With Censored Regression Models, _Journal of the American Statistical Association_, 102:478, 527-537, https://doi.org/10.1198/016214507000000149
