---
title: "Simulated Example"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Simulated Example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(DPH)
```

Here is a simulated example which shows you how to use DPH:

```{r example}
sim_data
```

```{r}
time <- sim_data$time
status <- sim_data$status
pred <- sim_data[, -(1:2)]
```

Outcome summary of the simulated data:

```{r table}
tbl <- table(time, status)
addmargins(tbl)
```

## Standard DPH Model

```{r model}
dph(
  time = time, 
  status = status, 
  pred = pred
)
```

## Adjusted DPH Model

### Case 1

```{r}
adph(
  time = time, 
  status = status, 
  pred = pred,
  sens = 0.8,
  spec = 0.9
)
```

### Case 2

```{r}
adph(
  time = time, 
  status = status, 
  pred = pred,
  sens = 0.8,
  spec = 0.9,
  sens_known = FALSE
)
```

### Case 3

```{r}
adph(
  time = time, 
  status = status, 
  pred = pred,
  sens = 0.8,
  spec = 0.9,
  spec_known = FALSE
)
```

### Case 4

```{r}
adph(
  time = time, 
  status = status, 
  pred = pred,
  sens = 0.8,
  spec = 0.9,
  sens_known = FALSE,  
  spec_known = FALSE
)
```

```{r}
proc.time()
```

